experiments:
  galton_triangle_matrix:
    # Small experiments
    - height: 5
      balls: 100
    - height: 5
      balls: 1000
      
    # Medium experiments  
    - height: 10
      balls: 500
    - height: 10
      balls: 5000
    - height: 20
      balls: 1000
    - height: 20
      balls: 10000
      

  galton_binomial:
    # Satndard variation of balls and height
    - heights: [5, 10, 15, 20, 25]
      balls_list: [100, 500, 1000, 5000, 10000]
      
    - heights: [30, 40, 50, 60, 70]
      balls_list: [2500, 5000, 10000, 25000, 50000]
      
      
    # Extreme cases
    - heights: [200, 250, 300, 400, 500]
      balls_list: [200, 250, 300, 400, 500]
      
    - heights:  [2500, 5000, 10000, 25000]
      balls_list: [100, 5000, 10000, 500000]

    - heights: [20, 25, 30, 35, 40]
      balls_list: [5, 10, 15, 20, 25]


  binomial_normal:
      
    # Changing N
    - n_values: [60, 70, 80, 90, 100, 125, 150, 175, 200]
      N: 1000
      
    # Medium n values
    - n_values: [60, 70, 80, 90, 100, 125, 150, 175, 200]
      N: 50000
      